### ISSUE TITLE
Lab 5 : Ollama Auto1111

### ISSUE THREAD

**Issue by juleshenry** [aimug-org/austin_langchain#42]
pip install is no longer up to date : "torch==2.1.2 torchvision==0.16.2" deprecated.

```
RuntimeError: Couldn't install torch.
Command: "{...}/stable-diffusion-webui/venv/bin/python3" -m pip install torch==2.1.2 torchvision==0.16.2 --extra-index-url https://download.pytorch.org/whl/cu121
```
Fix is:
`
pip3 install torch==2.2.0 torchvision==0.17.0 --extra-index-url https://download.pytorch.org/whl/cu121`

**Comment by lalanikarim** [comment]
@juleshenry What step are you running into this error?
